# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jemmy's Blog
subtitle: 保持专注
description: 今日事，今日毕
keywords: Golang,Python,blog
author: Jemmy
language: zh-CN
timezone: "Asia/Shanghai"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.hujm.net
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
#external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
# highlight:
#   enable: true
#   auto_detect: true
#   line_number: true
#   tab_replace: ""
# highlight:
#   enable: false
#   auto_detect: true
#   line_number: true
#   tab_replace:

prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "tomorrow"
  line_number: false # default false
  custom_css:

auto_excerpt:
  enable: false
  length: 150

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

#Markdown
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
    - markdown-it-imsize
    - markdown-it-mark
    - markdown-it-regexp
    - markdown-it-task-checkbox
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: info
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
    - markdown-it-deflist
    - name: markdown-it-emoji
      options:
        shortcuts: {}
  anchors:
    level: 1
    collisionSuffix: "v"
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ""

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-mark
        enable: false
    - plugin:
        name: "@neilsustc/markdown-it-katex"
        enable: true
        options:
          strict: false
# TOC
toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: "#"
    style: header-anchor
  enable: true
  number: true
  auto_open: true # auto open the sidebar

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
# plugins:
#  - hexo-generator-feed
#  - hexo-generator-baidu-sitemap
#  - hexo-generator-sitemap

theme: butterfly
# theme: even
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/JemmyH/jemmyh.github.io
  branch: master

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xm

# feed:
#   type: atom
#   path: atom.xml
#   limit: 100

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

# # menu 菜单配置
# menu:
#   首页: / || fas fa-home
#   归档: /archives/ || fas fa-archive
#   分类: /categories/ || fas fa-folder-open
#   关于我: /about/ || fas fa-heart
#   enabled: true

# 搜索
search:
  path: search.xml
  field: post

# 中文转拼音
permalink_pinyin:
  enable: true
  separator: "-" # default: '-'

# 文章统计
postInfo:
  date: true
  update: false
  wordCount: true # 设置文章字数统计为 true.
  totalCount: false # 设置站点文章总字数统计为 true.
  min2read: false # 阅读时长.
  readCount: true # 阅读次数.

# emoj表情支持
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

# RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date

# 是否在首页显示音乐
music:
  enable: true
  title: # 非吸底模式有效
    enable: true
    show: 听听音乐
  server: netease # require music platform: netease, tencent, kugou, xiami, baidu
  type: search # require song, playlist, album, search, artist
  id: 赵雷 # require song id / playlist id / album id / search keyword
  fixed: false # 开启吸底模式
  autoplay: false # 是否自动播放
  theme: "#42b983"
  loop: "all" # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: "random" # 音频循环顺序, 可选值: 'list', 'random'
  preload: "auto" # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true # 列表默认折叠

# butteryfly
highlight_theme: light # default / darker / pale night / light / ocean / mac / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
code_word_wrap: false

# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true
  copyright: false  //这里改成true就可以看到你的版权协议

social:
  fab fa-github: https://github.com/JemmyH || Github
  fas fa-envelope: mailto:hujm20151021@gmail.com || Email

# MathJax   //数学公式，我用的是katex
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: true
  per_page: true
  hide_scrollbar: true

# Favicon（網站圖標）
favicon: /img/favicon.png

# Avatar (頭像)
avatar:
  img: https://avatars1.githubusercontent.com/u/38834787?s=460&u=86d024163fa24335179b43e01806edb2baba6ddc&v=4
  effect: false
